"""Add column accounts.full_name

Revision ID: 26f5cf01525b
Revises: ca867081146e
Create Date: 2019-10-26 21:43:31.750276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f5cf01525b'
down_revision = 'ca867081146e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('full_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'full_name')
    # ### end Alembic commands ###
