"""Substitute Category table to Account

Revision ID: cdd227c0801b
Revises: f7d2ed2fba47
Create Date: 2019-01-27 08:59:31.073796

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cdd227c0801b'
down_revision = 'f7d2ed2fba47'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('items')
    op.drop_table('dictionaries')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('receipt_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('sum', sa.Integer(), nullable=False),
                    sa.Column(
                        'account_guid', sa.String(length=32), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['account_guid'],
                        ['accounts.guid'],
                    ),
                    sa.ForeignKeyConstraint(
                        ['receipt_id'],
                        ['receipts.id'],
                    ), sa.PrimaryKeyConstraint('id'))
    op.create_table('dictionaries',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column(
                        'account_guid', sa.String(length=32), nullable=False),
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.Column('phrase', sa.String(), nullable=False),
                    sa.Column('weight', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['account_guid'],
                        ['accounts.guid'],
                    ), sa.ForeignKeyConstraint(
                        ['item_id'],
                        ['items.id'],
                    ), sa.PrimaryKeyConstraint('id'))
    op.drop_table('categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories', sa.Column(
        'id', sa.INTEGER(), nullable=False),
                    sa.Column('code', sa.VARCHAR(), nullable=False),
                    sa.PrimaryKeyConstraint('id'))
    op.drop_table('dictionaries')
    op.drop_table('items')
    # ### end Alembic commands ###

    op.create_table('items', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('receipt_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('sum', sa.Integer(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['category_id'],
                        ['categories.id'],
                    ),
                    sa.ForeignKeyConstraint(
                        ['receipt_id'],
                        ['receipts.id'],
                    ), sa.PrimaryKeyConstraint('id'))
    op.create_table('dictionaries',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.Column('phrase', sa.String(), nullable=False),
                    sa.Column('weight', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['category_id'],
                        ['categories.id'],
                    ), sa.ForeignKeyConstraint(
                        ['item_id'],
                        ['items.id'],
                    ), sa.PrimaryKeyConstraint('id'))
